---@class Vehicle
---@field name string
---@field brand string
---@field model string
---@field price number
---@field category string
---@field hash string | integer actually just an integer but string is required for types to align when using `asbo` for example

---@type table<string, Vehicle>
return {
	--- D Class
	akuma = {
		name = 'Akuma',
		brand = 'Dinka',
		model = 'akuma',
		price = 18000,
		category = 'motorcycles',
		hash = `akuma`,
	},
	asea = {
		name = 'Asea',
		brand = 'Declasse',
		model = 'asea',
		price = 6000,
		category = 'lowincome',
		hash = `asea`,
	},
	bagger = {
		name = 'Bagger',
		brand = 'WMC',
		model = 'bagger',
		price = 22500,
		category = 'motorcycles',
		hash = `bagger`,
	},
	baller = {
		name = 'Baller',
		brand = 'Gallivanter',
		model = 'baller',
		price = 23000,
		category = 'suvs',
		hash = `baller`,
	},
	baller4 = {
		name = 'Baller LE LWB',
		brand = 'Gallivanter',
		model = 'baller4',
		price = 25000,
		category = 'suvs',
		hash = `baller4`,
	},
	baller7 = {
		name = 'Baller ST',
		brand = 'Gallivanter',
		model = 'baller7',
		price = 25000,
		category = 'suvs',
		hash = `baller7`,
	},
	bfinjection = {
		name = 'Injection',
		brand = 'BF',
		model = 'bfinjection',
		price = 20000,
		category = 'offroad',
		hash = `bfinjection`,
	},
	bifta = {
		name = 'Bifta',
		brand = 'BF',
		model = 'bifta',
		price = 21000,
		category = 'offroad',
		hash = `bifta`,
	},
	boattrailer = {
		name = 'Boat Trailer',
		brand = ' ',
		model = 'boattrailer',
		price = 12000,
		category = 'utility',
		hash = `boattrailer`,
	},
	bison = {
		name = 'Bison',
		brand = 'Bravado',
		model = 'bison',
		price = 16000,
		category = 'offroad',
		hash = `bison`,
	},
	bjxl = {
		name = 'BeeJay XL',
		brand = 'Karin',
		model = 'bjxl',
		price = 22500,
		category = 'suvs',
		hash = `bjxl`,
	},
	blazer = {
		name = 'Blazer',
		brand = 'Nagasaki',
		model = 'blazer',
		price = 9500,
		category = 'motorcycles',
		hash = `blazer`,
	},
	blazer4 = {
		name = 'Street Blazer',
		brand = 'Nagasaki',
		model = 'blazer4',
		price = 14500,
		category = 'motorcycles',
		hash = `blazer4`,
	},
	bmx = {
		name = 'BMX',
		brand = ' ',
		model = 'bmx',
		price = 160,
		category = 'cycles',
		hash = `bmx`,
	},
	bobcatxl = {
		name = 'Bobcat XL',
		brand = 'Vapid',
		model = 'bobcatxl',
		price = 24000,
		category = 'offroad',
		hash = `bobcatxl`,
	},
	bodhi2 = {
		name = 'Bodhi',
		brand = 'Canis',
		model = 'bodhi2',
		price = 5000,
		category = 'lowincome',
		hash = `bodhi2`,
	},
	burrito = {
		name = 'Burrito',
		brand = 'Declasse',
		model = 'burrito',
		price = 25000,
		category = 'utility',
		hash = `burrito`,
	},
	tr2 = {
		name = 'Car Hauler',
		brand = ' ',
		model = 'tr2',
		price = 20000,
		category = 'utility',
		hash = `tr2`,
	},
	camper = {
		name = 'Camper',
		brand = 'Brute',
		model = 'camper',
		price = 20000,
		category = 'vans',
		hash = `camper`,
	},
	cavalcade2 = {
		name = 'Cavalcade',
		brand = 'Albany',
		model = 'cavalcade2',
		price = 25000,
		category = 'suvs',
		hash = `cavalcade2`,
	},
	chimera = {
		name = 'Chimera',
		brand = 'Nagasaki',
		model = 'chimera',
		price = 18500,
		category = 'motorcycles',
		hash = `chimera`,
	},
	chino2 = {
		name = 'Chino Custom',
		brand = 'Vapid',
		model = 'chino2',
		price = 24000,
		category = 'muscle',
		hash = `chino2`,
	},
	cliffhanger = {
		name = 'Cliffhanger',
		brand = 'WMC',
		model = 'cliffhanger',
		price = 16500,
		category = 'motorcycles',
		hash = `cliffhanger`,
	},
	cruiser = {
		name = 'Cruiser',
		brand = ' ',
		model = 'cruiser',
		price = 510,
		category = 'cycles',
		hash = `cruiser`,
	},
	daemon = {
		name = 'Daemon',
		brand = 'WMC',
		model = 'daemon',
		price = 12500,
		category = 'motorcycles',
		hash = `daemon`,
	},
	daemon2 = {
		name = 'Daemon High',
		brand = 'WMC',
		model = 'daemon2',
		price = 14000,
		category = 'motorcycles',
		hash = `daemon2`,
	},
	dune = {
		name = 'Dune Buggy',
		brand = 'BF',
		model = 'dune',
		price = 12000,
		category = 'offroad',
		hash = `dune`,
	},
	emperor = {
		name = 'Emperor',
		brand = 'Albany',
		model = 'emperor',
		price = 11000,
		category = 'sedans',
		hash = `emperor`,
	},
	emperor2 = {
		name = 'Emperor Beater',
		brand = 'Albany',
		model = 'emperor2',
		price = 6000,
		category = 'lowiincome',
		hash = `emperor2`,
	},
	enduro = {
		name = 'Enduro',
		brand = 'Dinka',
		model = 'enduro',
		price = 11500,
		category = 'motorcycles',
		hash = `enduro`,
	},
	faction = {
		name = 'Emperor',
		brand = 'Willard',
		model = 'faction',
		price = 16500,
		category = 'muscle',
		hash = `faction`,
	},
	faction3 = {
		name = 'Faction XL',
		brand = 'Willard',
		model = 'faction3',
		price = 24000,
		category = 'muscle',
		hash = `faction3`,
	},
	fagaloa = {
		name = 'Fagaloa',
		brand = 'Vulcar',
		model = 'fagaloa',
		price = 14500,
		category = 'sportsclassics',
		hash = `fagaloa`,
	},
	faggio = {
		name = 'Faggio Sport',
		brand = 'Pincipe',
		model = 'faggio',
		price = 8000,
		category = 'motorcycles',
		hash = `faggio`,
	},
	faggio2 = {
		name = 'Faggio',
		brand = 'Pincipe',
		model = 'faggio2',
		price = 7500,
		category = 'motorcycles',
		hash = `faggio2`,
	},
	fcr = {
		name = 'FCR 1000',
		brand = 'Pegassi',
		model = 'fcr',
		price = 22000,
		category = 'motorcycles',
		hash = `fcr`,
	},
	fcr2 = {
		name = 'FCR 1000 Custom',
		brand = 'Pegassi',
		model = 'fcr2',
		price = 24000,
		category = 'motorcycles',
		hash = `fcr2`,
	},
	fixter = {
		name = 'Fixter',
		brand = ' ',
		model = 'fixter',
		price = 225,
		category = 'cycles',
		hash = `fixter`,
	},
	flatbed = {
		name = 'Flatbed',
		brand = 'MTR',
		model = 'flatbed',
		price = 25000,
		category = 'utility',
		hash = `flatbed`,
	},
	fq2 = {
		name = 'FQ 2',
		brand = 'Fathom',
		model = 'fq2',
		price = 25000,
		category = 'suvs',
		hash = `fq2`,
	},
	freecrawler = {
		name = 'Freecrawler',
		brand = 'Canis',
		model = 'freecrawler',
		price = 24000,
		category = 'offroad',
		hash = `freecrawler`,
	},
	gargoyle = {
		name = 'Gargoyle',
		brand = 'WMC',
		model = 'gargoyle',
		price = 13500,
		category = 'motorcycles',
		hash = `gargoyle`,
	},
	gburrito = {
		name = 'Burrito G',
		brand = 'Declasse',
		model = 'gburrito',
		price = 12000,
		category = 'utility',
		hash = `gburrito`,
	},
	gburrito2 = {
		name = 'Burrito GL',
		brand = 'Declasse',
		model = 'gburrito2',
		price = 12000,
		category = 'utility',
		hash = `gburrito2`,
	},
	glendale = {
		name = 'Glendale',
		brand = 'Benefactor',
		model = 'glendale',
		price = 18000,
		category = 'sedans',
		hash = `glendale`,
	},
	glendale2 = {
		name = 'Glendale Custom',
		brand = 'Benefactor',
		model = 'glendale2',
		price = 18000,
		category = 'sedans',
		hash = `glendale2`,
	},
	granger = {
		name = 'Granger',
		brand = 'Declasse',
		model = 'granger',
		price = 24000,
		category = 'suvs',
		hash = `granger`,
	},
	gresley = {
		name = 'Gresley',
		brand = 'Bravado',
		model = 'gresley',
		price = 23000,
		category = 'suvs',
		hash = `gresley`,
	},
	guardian = {
		name = 'Guardian',
		brand = 'Vapid',
		model = 'guardian',
		price = 15000,
		category = 'offroad',
		hash = `guardian`,
	},
	habanero = {
		name = 'Habanero',
		brand = 'Emperor',
		model = 'habanero',
		price = 21000,
		category = 'suvs',
		hash = `habanero`,
	},
	hexer = {
		name = 'Hexer',
		brand = 'LCC',
		model = 'hexer',
		price = 17500,
		category = 'motorcycles',
		hash = `hexer`,
	},
	ingot = {
		name = 'Ingot',
		brand = 'Vulcar',
		model = 'ingot',
		price = 19500,
		category = 'sedans',
		hash = `ingot`,
	},
	innovation = {
		name = 'Innovation',
		brand = 'LCC',
		model = 'innovation',
		price = 19500,
		category = 'motorcycles',
		hash = `innovation`,
	},
	issi2 = {
		name = 'Issi',
		brand = 'Weeny',
		model = 'issi2',
		price = 8500,
		category = 'compacts',
		hash = `issi2`,
	},
	issi3 = {
		name = 'Issi Classic',
		brand = 'Weeny',
		model = 'issi3',
		price = 12000,
		category = 'compacts',
		hash = `issi3`,
	},
	journey = {
		name = 'Journey',
		brand = 'Zirconium',
		model = 'journey',
		price = 5000,
		category = 'utility',
		hash = `journey`,
	},
	kalahari = {
		name = 'Kalahari',
		brand = 'Canis',
		model = 'kalahari',
		price = 17500,
		category = 'offroad',
		hash = `kalahari`,
	},
	kamacho = {
		name = 'Kamacho',
		brand = 'Canis',
		model = 'kamacho',
		price = 17500,
		category = 'offroad',
		hash = `kamacho`,
	},
	landstalker = {
		name = 'Landstalker',
		brand = 'Dundreary',
		model = 'landstalker',
		price = 23000,
		category = 'suvs',
		hash = `landstalker`,
	},
	manana = {
		name = 'Manana',
		brand = 'Albany',
		model = 'manana',
		price = 19500,
		category = 'sportsclassics',
		hash = `manana`,
	},
	minivan = {
		name = 'Minivan',
		brand = 'Vapid',
		model = 'minivan',
		price = 18000,
		category = 'vans',
		hash = `minivan`,
	},
	minivan2 = {
		name = 'Minivan Custom',
		brand = 'Vapid',
		model = 'minivan2',
		price = 22000,
		category = 'vans',
		hash = `minivan2`,
	},
	nemesis = {
		name = 'Nemesis',
		brand = 'Principe',
		model = 'nemesis',
		price = 16500,
		category = 'motorcycles',
		hash = `nemesis`,
	},
	panto = {
		name = 'Panto',
		brand = 'Benefactor',
		model = 'panto',
		price = 7500,
		category = 'compacts',
		hash = `panto`,
	},
	paradise = {
		name = 'Paradise',
		brand = 'Bravado',
		model = 'paradise',
		price = 15000,
		category = 'vans',
		hash = `paradise`,
	},
	patriot = {
		name = 'Patriot',
		brand = 'Mammoth',
		model = 'patriot',
		price = 20000,
		category = 'suvs',
		hash = `patriot`,
	},
	patriot2 = {
		name = 'Patriot Stretch',
		brand = 'Mammoth',
		model = 'patriot2',
		price = 24000,
		category = 'utility',
		hash = `patriot2`,
	},
	patriot3 = {
		name = 'Patriot Mil-Spec',
		brand = 'Weeny',
		model = 'patriot3',
		price = 25000,
		category = 'offroad',
		hash = `patriot3`,
	},
	peyote = {
		name = 'Peyote',
		brand = 'Vapid',
		model = 'peyote',
		price = 12000,
		category = 'muscle',
		hash = `peyote`,
	},
	phantom = {
		name = 'Phantom',
		brand = 'Jobuilt',
		model = 'phantom',
		price = 24000,
		category = 'utility',
		hash = `phantom`,
	},
	picador = {
		name = 'Picador',
		brand = 'Cheval',
		model = 'picador',
		price = 19500,
		category = 'muscle',
		hash = `picador`,
	},
	pigalle = {
		name = 'Pigalle',
		brand = 'Lampadati',
		model = 'pigalle',
		price = 24000,
		category = 'sportsclassics',
		hash = `pigalle`,
	},
	prairie = {
		name = 'Prairie',
		brand = 'Bollokan',
		model = 'prairie',
		price = 24000,
		category = 'coupes',
		hash = `prairie`,
	},
	primo = {
		name = 'Primo',
		brand = 'Albany',
		model = 'primo',
		price = 22500,
		category = 'sedans',
		hash = `primo`,
	},
	primo2 = {
		name = 'Primo Custom',
		brand = 'Albany',
		model = 'primo2',
		price = 24500,
		category = 'sedans',
		hash = `primo2`,
	},
	radi = {
		name = 'Radius',
		brand = 'Vapid',
		model = 'issi2',
		price = 29000,
		category = 'suvs',
		hash = `radi`,
	},
	rancherxl = {
		name = 'Rancher XL',
		brand = 'Declasse',
		model = 'rancherxl',
		price = 15000,
		category = 'suvs',
		hash = `rancherxl`,
	},
	ratbike = {
		name = 'Rat Bike',
		brand = 'WMC',
		model = 'ratbike',
		price = 15000,
		category = 'motorcycles',
		hash = `ratbike`,
	},
	rebel2 = {
		name = 'Rebel',
		brand = 'Karin',
		model = 'rebel2',
		price = 15500,
		category = 'offroad',
		hash = `rebel2`,
	},
	rebla = {
		name = 'Rebla GTS',
		brand = 'Übermacht',
		model = 'rebla',
		price = 17000,
		category = 'suvs',
		hash = `rebla`,
	},
	regina = {
		name = 'Regina',
		brand = 'Dundreary',
		model = 'regina',
		price = 15500,
		category = 'sedans',
		hash = `regina`,
	},
	rhapsody = {
		name = 'Rhapsody',
		brand = 'Declasse',
		model = 'rhapsody',
		price = 5500,
		category = 'lowincome',
		hash = `rhapsody`,
	},
	riata = {
		name = 'Riata',
		brand = 'Vapid',
		model = 'riata',
		price = 21000,
		category = 'offroad',
		hash = `riata`,
	},
	ratloader = {
		name = 'Rat-Loader',
		brand = 'Bravado',
		model = 'ratloader',
		price = 20000,
		category = 'offroad',
		hash = `ratloader`,
	},
	ratloader2 = {
		name = 'Rat-Truck',
		brand = 'Bravado',
		model = 'ratloader2',
		price = 20000,
		category = 'offroad',
		hash = `ratloader2`,
	},
	rocoto = {
		name = 'Rocoto',
		brand = 'Obey',
		model = 'rocoto',
		price = 22500,
		category = 'suvs',
		hash = `rocoto`,
	},
	btype = {
		name = 'Roosevelt',
		brand = 'Albany',
		model = 'btype',
		price = 23500,
		category = 'muscle',
		hash = `btype`,
	},
	btype3 = {
		name = 'Roosevelt Valor',
		brand = 'Albany',
		model = 'btype3',
		price = 24500,
		category = 'muscle',
		hash = `btype3`,
	},
	ruffian = {
		name = 'Ruffian',
		brand = 'Pegassi',
		model = 'ruffian',
		price = 17500,
		category = 'motorcycles',
		hash = `ruffian`,
	},
	rumpo = {
		name = 'Rumpo',
		brand = 'Bravado',
		model = 'rumpo',
		price = 15000,
		category = 'vans',
		hash = `rumpo`,
	},
	rumpo3 = {
		name = 'Rumpo Trail',
		brand = 'Bravado',
		model = 'rumpo3',
		price = 8500,
		category = 'vans',
		hash = `rumpo3`,
	},
	sandking = {
		name = 'Sandking XL',
		brand = 'Vapid',
		model = 'sandking',
		price = 25000,
		category = 'offroad',
		hash = `sandking`,
	},
	sandking2 = {
		name = 'Sandking SWB',
		brand = 'Vapid',
		model = 'sandking2',
		price = 23500,
		category = 'offroad',
		hash = `sandking2`,
	},
	scorcher = {
		name = 'Scorcher',
		brand = ' ',
		model = 'scorcher',
		price = 280,
		category = 'cycles',
		hash = `scorcher`,
	},
-------------------------------------
	seminole = {
		name = 'Seminole',
		brand = 'Canis',
		model = 'seminole',
		price = 22000,
		category = 'suvs',
		hash = `seminole`,
	},
	seminole2 = {
		name = 'Seminole Frontier',
		brand = 'Canis',
		model = 'seminole2',
		price = 24000,
		category = 'suvs',
		hash = `seminole2`,
	},
	serrano = {
		name = 'Serrano',
		brand = 'Benefactor',
		model = 'serrano',
		price = 22500,
		category = 'suvs',
		hash = `serrano`,
	},
	slamtruck = {
		name = 'Slamtruck',
		brand = 'Vapid',
		model = 'slamtruck',
		price = 24000,
		category = 'utility',
		hash = `slamtruck`,
	},
	slamvan2 = {
		name = 'Lost Slamvan',
		brand = 'Vapid',
		model = 'slamvan2',
		price = 25000,
		category = 'muscle',
		hash = `slamvan2`,
	},
	speedo4 = {
		name = 'Speedo Custom',
		brand = 'Vapid',
		model = 'speedo4',
		price = 22300,
		category = 'vans',
		hash = `speedo4`,
	},
	stalion = {
		name = 'Stallion',
		brand = 'Declasse',
		model = 'stalion',
		price = 15000,
		category = 'muscle',
		hash = `stalion`,
	},
	stalion2 = {
		name = 'Stallion R',
		brand = 'Declasse',
		model = 'stalion2',
		price = 19000,
		category = 'tuner',
		hash = `stalion2`,
	},
	stanier = {
		name = 'Stanier',
		brand = 'Vapid',
		model = 'stanier',
		price = 19000,
		category = 'muscle',
		hash = `stanier`,
	},
	stretch = {
		name = 'Stretch',
		brand = 'Albany',
		model = 'stretch',
		price = 25000,
		category = 'utility',
		hash = `stretch`,
	},
	surfer = {
		name = 'Surfer',
		brand = 'BF',
		model = 'surfer',
		price = 18500,
		category = 'vans',
		hash = `surfer`,
	},
	surfer2 = {
		name = 'Surfer Beater',
		brand = 'BF',
		model = 'surfer2',
		price = 6500,
		category = 'lowincome',
		hash = `surfer2`,
	},
	taco = {
		name = 'Taco Van',
		brand = 'Brute',
		model = 'taco',
		price = 25000,
		category = 'utility',
		hash = `taco`,
	},
	tornado = {
		name = 'Tornado',
		brand = 'Declasse',
		model = 'tornado',
		price = 5000,
		category = 'lowincome',
		hash = `tornado`,
	},
	tornado5 = {
		name = 'Tornado Custom',
		brand = 'Declasse',
		model = 'tornado5',
		price = 20000,
		category = 'muscle',
		hash = `tornado5`,
	},
	towtruck = {
		name = 'Towtruck XL',
		brand = 'Vapid',
		model = 'towtruck',
		price = 15000,
		category = 'utility',
		hash = `towtruck`,
	},
	towtruck2 = {
		name = 'Towtruck',
		brand = 'Vapid',
		model = 'towtruck2',
		price = 15000,
		category = 'utility',
		hash = `towtruck2`,
	},
	tribike = {
		name = 'Whippet Race Bike',
		brand = ' ',
		model = 'tribike',
		price = 520,
		category = 'cycles',
		hash = `tribike`,
	},
	tribike2 = {
		name = 'Endurance Race Bike',
		brand = ' ',
		model = 'tribike2',
		price = 520,
		category = 'cycles',
		hash = `tribike2`,
	},
	tribike3 = {
		name = 'Tri-Cycles Race Bike',
		brand = ' ',
		model = 'tribike3',
		price = 520,
		category = 'cycles',
		hash = `tribike3`,
	},
	vader = {
		name = 'Vader',
		brand = 'Shitzu',
		model = 'vader',
		price = 14500,
		category = 'motorcycles',
		hash = `vader`,
	},
	vagrant = {
		name = 'Vagrant',
		brand = 'Maxwell',
		model = 'vagrant',
		price = 12000,
		category = 'offroad',
		hash = `vagrant`,
	},
	virgo = {
		name = 'Virgo',
		brand = 'Albany',
		model = 'virgo',
		price = 16500,
		category = 'muscle',
		hash = `virgo`,
	},
	voodoo = {
		name = 'Voodoo',
		brand = 'Declasse',
		model = 'voodoo',
		price = 21500,
		category = 'muscle',
		hash = `voodoo`,
	},
	voodoo2 = {
		name = 'Voodoo Custom',
		brand = 'Declasse',
		model = 'voodoo2',
		price = 22000,
		category = 'muscle',
		hash = `voodoo2`,
	},
	washington = {
		name = 'Washington',
		brand = 'Albany',
		model = 'washington',
		price = 17000,
		category = 'sedans',
		hash = `washington`,
	},
	youga = {
		name = 'Youga',
		brand = 'Bravado',
		model = 'youga',
		price = 13000,
		category = 'vans',
		hash = `youga`,
	},
	youga2 = {
		name = 'Youga Classic',
		brand = 'Bravado',
		model = 'youga2',
		price = 12000,
		category = 'vans',
		hash = `youga2`,
	},
	zombiea = {
		name = 'Zombie Bobber',
		brand = 'WMC',
		model = 'zombiea',
		price = 17500,
		category = 'motorcycles',
		hash = `zombiea`,
	},
	zombieb = {
		name = 'Zombie Chopper',
		brand = 'WMC',
		model = 'zombieb',
		price = 18000,
		category = 'motorcycles',
		hash = `zombieb`,
	},
	--- C Class
	asterope = {
		name = 'Asterope',
		brand = 'Karin',
		model = 'asterope',
		price = 29000,
		category = 'sedans',
		hash = `asterope`,
	},
	avarus = {
		name = 'Avarus',
		brand = 'LCC',
		model = 'avarus',
		price = 32500,
		category = 'motorcycles',
		hash = `avarus`,
	},
	bf400 = {
		name = 'BF400',
		brand = 'Nagasaki',
		model = 'bf400',
		price = 45000,
		category = 'motorcycles',
		hash = `bf400`,
	},
	blade = {
		name = 'Blade',
		brand = 'Vapid',
		model = 'blade',
		price = 38500,
		category = 'muscle',
		hash = `blade`,
	},
	blista = {
		name = 'Blista',
		brand = 'Dinka',
		model = 'blista',
		price = 35000,
		category = 'compacts',
		hash = `blista`,
	},
	brioso2 = {
		name = 'Brioso R/A',
		brand = 'Grotti',
		model = 'brioso2',
		price = 36000,
		category = 'compacts',
		hash = `brioso2`,
	},
	buccaneer = {
		name = 'Buccaneer',
		brand = 'Albany',
		model = 'buccaneer',
		price = 26000,
		category = 'muscle',
		hash = `buccaneer`,
	},
	buccaneer2 = {
		name = 'Buccaneer Custom',
		brand = 'Albany',
		model = 'buccaneer2',
		price = 29000,
		category = 'muscle',
		hash = `buccaneer2`,
	},
	caracara2 = {
		name = 'Caracara 4x4',
		brand = 'Vapid',
		model = 'caracara2',
		price = 50000,
		category = 'offroad',
		hash = `caracara2`,
	},
	casco = {
		name = 'Casco',
		brand = 'Lampadati',
		model = 'casco',
		price = 48000,
		category = 'sportsclassics',
		hash = `casco`,
	},
	chino = {
		name = 'Chino',
		brand = 'Vapid',
		model = 'chino',
		price = 29000,
		category = 'muscle',
		hash = `chino`,
	},
	club = {
		name = 'Club',
		brand = 'BF',
		model = 'club',
		price = 40000,
		category = 'compacts',
		hash = `club`,
	},
	cog55 = {
		name = 'Cognoscenti 55',
		brand = 'Enus',
		model = 'cog55',
		price = 50000,
		category = 'sedans',
		hash = `cog55`,
	},
	cogcabrio = {
		name = 'Cognoscenti Cabrio',
		brand = 'Enus',
		model = 'cogcabrio',
		price = 48000,
		category = 'coupes',
		hash = `cogcabrio`,
	},
	cognoscenti = {
		name = 'Cognoscenti',
		brand = 'Enus',
		model = 'cognoscenti',
		price = 49000,
		category = 'sedans',
		hash = `cognoscenti`,
	},
	defiler = {
		name = 'Defiler',
		brand = 'Shitzu',
		model = 'defiler',
		price = 39000,
		category = 'motorcycles',
		hash = `defiler`,
	},
	double = {
		name = 'Double T',
		brand = 'Dinka',
		model = 'double',
		price = 28500,
		category = 'motorcycles',
		hash = `double`,
	},
	dubsta = {
		name = 'Dubsta',
		brand = 'Benefactor',
		model = 'dubsta',
		price = 42000,
		category = 'suvs',
		hash = `dubsta`,
	},
	esskey = {
		name = 'Esskey',
		brand = 'Pegassi',
		model = 'esskey',
		price = 31500,
		category = 'motorcycles',
		hash = `esskey`,
	},
	exemplar = {
		name = 'Exemplar',
		brand = 'Dewbauchee',
		model = 'exemplar',
		price = 40000,
		category = 'coupes',
		hash = `exemplar`,
	},
	f620 = {
		name = 'F620',
		brand = 'Ocelot',
		model = 'f620',
		price = 37000,
		category = 'coupes',
		hash = `f620`,
	},
	felon = {
		name = 'Felon',
		brand = 'Lampadati',
		model = 'felon',
		price = 38000,
		category = 'sedans',
		hash = `felon`,
	},
	felon2 = {
		name = 'Felon GT',
		brand = 'Lampadati',
		model = 'felon2',
		price = 45000,
		category = 'coupes',
		hash = `felon2`,
	},
	fusilade = {
		name = 'Fusilade',
		brand = 'Schyster',
		model = 'fusilade',
		price = 45000,
		category = 'sports',
		hash = `fusilade`,
	},
	greenwood = {
		name = 'Greenwood',
		brand = 'Bravado',
		model = 'greenwood',
		price = 26000,
		category = 'muscle',
		hash = `greenwood`,
	},
	hakuchou = {
		name = 'Hakuchou',
		brand = 'Shitzu',
		model = 'hakuchou',
		price = 38500,
		category = 'motorcycles',
		hash = `hakuchou`,
	},
	hermes = {
		name = 'Hermes',
		brand = 'Albany',
		model = 'hermes',
		price = 28000,
		category = 'muscle',
		hash = `hermes`,
	},
	hotknife = {
		name = 'Hotknife',
		brand = 'Vapid',
		model = 'hotknife',
		price = 35000,
		category = 'muscle',
		hash = `hotknife`,
	},
	huntley = {
		name = 'Huntley S',
		brand = 'Enus',
		model = 'huntley',
		price = 44000,
		category = 'suvs',
		hash = `huntley`,
	},
	hustler = {
		name = 'Hustler',
		brand = 'Vapid',
		model = 'hustler',
		price = 40000,
		category = 'muscle',
		hash = `hustler`,
	},
	intruder = {
		name = 'Intruder',
		brand = 'Karin',
		model = 'intruder',
		price = 39500,
		category = 'sedans',
		hash = `intruder`,
	},
	jubilee = {
		name = 'Jubilee',
		brand = 'Enus',
		model = 'jubilee',
		price = 49000,
		category = 'suvs',
		hash = `jubilee`,
	},
	kuruma = {
		name = 'Kuruma',
		brand = 'Karin',
		model = 'kuruma',
		price = 50000,
		category = 'tuner',
		hash = `kuruma`,
	},
	locust = {
		name = 'Locust',
		brand = 'Ocelot',
		model = 'locust',
		price = 45000,
		category = 'sports',
		hash = `locust`,
	},
	lurcher = {
		name = 'Lurcher',
		brand = 'Albany',
		model = 'lurcher',
		price = 35000,
		category = 'utility',
		hash = `lurcher`,
	},
	manchez = {
		name = 'Manchez',
		brand = 'Maibatsu',
		model = 'manchez',
		price = 34500,
		category = 'motorcycles',
		hash = `manchez`,
	},
	mesa = {
		name = 'Mesa',
		brand = 'Canis',
		model = 'mesa',
		price = 34000,
		category = 'suvs',
		hash = `mesa`,
	},
	mesa3 = {
		name = 'Mesa Trail',
		brand = 'Canis',
		model = 'mesa3',
		price = 38500,
		category = 'suvs',
		hash = `mesa3`,
	},
	michelli = {
		name = 'Michelli GT',
		brand = 'Lampadati',
		model = 'michelli',
		price = 38000,
		category = 'sportsclassics',
		hash = `michelli`,
	},
	monroe = {
		name = 'Monroe',
		brand = 'Pegassi',
		model = 'monroe',
		price = 35000,
		category = 'sportsclassics',
		hash = `monroe`,
	},
	moonbeam = {
		name = 'Moonbeam',
		brand = 'Declasse',
		model = 'moonbeam',
		price = 38000,
		category = 'vans',
		hash = `moonbeam`,
	},
	nightblade = {
		name = 'Nightblade',
		brand = 'LCC',
		model = 'nightblade',
		price = 27500,
		category = 'motorcycles',
		hash = `nightblade`,
	},
	penumbra = {
		name = 'Penumbra',
		brand = 'Maibatsu',
		model = 'penumbra',
		price = 36000,
		category = 'sports',
		hash = `penumbra`,
	},
	phoenix = {
		name = 'Phoenix',
		brand = 'Imponte',
		model = 'phoenix',
		price = 27000,
		category = 'muscle',
		hash = `phoenix`,
	},
	premier = {
		name = 'Premier',
		brand = 'Declasse',
		model = 'premier',
		price = 22000,
		category = 'sedans',
		hash = `premier`,
	},
	raptor = {
		name = 'Raptor',
		brand = 'BF',
		model = 'raptor',
		price = 35500,
		category = 'sports',
		hash = `raptor`,
	},
	reever = {
		name = 'Reever',
		brand = 'Western',
		model = 'reever',
		price = 45000,
		category = 'motorcycles',
		hash = `reever`,
	},
	rhinehart = {
		name = 'Rhinehart',
		brand = 'Übermacht',
		model = 'rhinehart',
		price = 35000,
		category = 'sports',
		hash = `rhinehart`,
	},
	ruiner = {
		name = 'Ruiner',
		brand = 'Imponte',
		model = 'ruiner',
		price = 40000,
		category = 'muscle',
		hash = `ruiner`,
	},
	sanchez = {
		name = 'Sanchez',
		brand = 'Maibatsu',
		model = 'sanchez',
		price = 46000,
		category = 'motorcycles',
		hash = `sanchez`,
	},
	sanchez2 = {
		name = 'Sanchez Sport',
		brand = 'Maibatsu',
		model = 'sanchez2',
		price = 36000,
		category = 'motorcycles',
		hash = `sanchez2`,
	},
	sanctus = {
		name = 'Sanctus',
		brand = 'LLC',
		model = 'sanctus',
		price = 39500,
		category = 'motorcycles',
		hash = `sanctus`,
	},
	slamvan3 = {
		name = 'Slamvan Custom',
		brand = 'Vapid',
		model = 'slamvan3',
		price = 35000,
		category = 'muscle',
		hash = `slamvan3`,
	},
	stafford = {
		name = 'Stafford',
		brand = 'Enus',
		model = 'stafford',
		price = 30000,
		category = 'sportsclassics',
		hash = `stafford`,
	},
	stinger = {
		name = 'Stinger',
		brand = 'Grotti',
		model = 'stinger',
		price = 42000,
		category = 'sportsclassics',
		hash = `stinger`,
	},
	stingergt = {
		name = 'Stinger GT',
		brand = 'Grotti',
		model = 'stingergt',
		price = 46000,
		category = 'sportsclassics',
		hash = `stingergt`,
	},
	swinger = {
		name = 'Swinger',
		brand = 'Ocelot',
		model = 'swinger',
		price = 28500,
		category = 'sportsclassics',
		hash = `swinger`,
	},
	tornado6 = {
		name = 'Tornado Rat Rod',
		brand = 'Declasse',
		model = 'tornado6',
		price = 29000,
		category = 'muscle',
		hash = `tornado6`,
	},
	vigero = {
		name = 'Vigero',
		brand = 'Declasse',
		model = 'vigero',
		price = 44000,
		category = 'muscle',
		hash = `vigero`,
	},
	virgo3 = {
		name = 'Virgo Classic',
		brand = 'Dundreary',
		model = 'virgo3',
		price = 36500,
		category = 'muscle',
		hash = `virgo3`,
	},
	vortex = {
		name = 'Vortex',
		brand = 'Pegassi',
		model = 'vortex',
		price = 49500,
		category = 'motorcycles',
		hash = `vortex`,
	},
	warrener = {
		name = 'Warrener',
		brand = 'Vulcar',
		model = 'warrener',
		price = 36500,
		category = 'sedans',
		hash = `warrener`,
	},
	warrener2 = {
		name = 'Warrener HKR',
		brand = 'Vulcar',
		model = 'warrener2',
		price = 45000,
		category = 'tuner',
		hash = `warrener2`,
	},
	xls = {
		name = 'XLS',
		brand = 'Benefactor',
		model = 'xls',
		price = 29000,
		category = 'suvs',
		hash = `xls`,
	},
	z190 = {
		name = '190z',
		brand = 'Karin',
		model = 'z190',
		price = 35000,
		category = 'sportsclassics',
		hash = `z190`,
	},
	zion = {
		name = 'Zion',
		brand = 'Übermacht',
		model = 'zion',
		price = 36500,
		category = 'coupes',
		hash = `zion`,
	},
	ztype = {
		name = 'Z-Type',
		brand = 'Truffade',
		model = 'ztype',
		price = 29000,
		category = 'sportsclassics',
		hash = `ztype`,
	},
	--- B Class
	astron = {
		name = 'Astron',
		brand = 'Pfister',
		model = 'astron',
		price = 140000,
		category = 'suvs',
		hash = `astron`,
	},
	blista2 = {
		name = 'Blista Compact',
		brand = 'Dinka',
		model = 'blista2',
		price = 116500,
		category = 'compacts',
		hash = `blista2`,
	},
	brawler = {
		name = 'Brawler',
		brand = 'Coil',
		model = 'brawler',
		price = 135000,
		category = 'offroad',
		hash = `brawler`,
	},
	brioso = {
		name = 'Brioso 300 Widebody',
		brand = 'Grotti',
		model = 'brioso',
		price = 110000,
		category = 'compacts',
		hash = `brioso`,
	},
	btype2 = {
		name = 'Fränken Stange',
		brand = 'Ablany',
		model = 'btype2',
		price = 118500,
		category = 'muscle',
		hash = `btype2`,
	},
	buffalo = {
		name = 'Buffalo',
		brand = 'Bravado',
		model = 'buffalo',
		price = 130000,
		category = 'muscle',
		hash = `buffalo`,
	},
	buffalo2 = {
		name = 'Buffalo S',
		brand = 'Bravado',
		model = 'buffalo2',
		price = 145000,
		category = 'muscle',
		hash = `buffalo2`,
	},
	cinquemila = {
		name = 'Cinquemila',
		brand = 'Lampadati',
		model = 'cinquemila',
		price = 135000,
		category = 'sports',
		hash = `cinquemila`,
	},
	comet2 = {
		name = 'Comet',
		brand = 'Pfister',
		model = 'comet2',
		price = 145000,
		category = 'sports',
		hash = `comet2`,
	},
	comet3 = {
		name = 'Comet Retro Custom',
		brand = 'Pfister',
		model = 'comet3',
		price = 150000,
		category = 'tuner',
		hash = `comet3`,
	},
	contender = {
		name = 'Contender',
		brand = 'Vapid',
		model = 'contender',
		price = 149000,
		category = 'offroad',
		hash = `contender`,
	},
	coquette3 = {
		name = 'Coquette BlackFin',
		brand = 'Invetero',
		model = 'coquette3',
		price = 120000,
		category = 'muscle',
		hash = `coquette3`,
	},
	dominator = {
		name = 'Dominator',
		brand = 'Vapid',
		model = 'dominator',
		price = 136000,
		category = 'muscle',
		hash = `dominator`,
	},
	dominator8 = {
		name = 'Dominator GTT',
		brand = 'Vapid',
		model = 'dominator8',
		price = 145000,
		category = 'muscle',
		hash = `dominator8`,
	},
	draugur = {
		name = 'Draugur',
		brand = 'Declasse',
		model = 'draugur',
		price = 100000,
		category = 'offroad',
		hash = `draugur`,
	},
	dukes = {
		name = 'Dukes',
		brand = 'Imponte',
		model = 'dukes',
		price = 130000,
		category = 'muscle',
		hash = `dukes`,
	},
	dukes3 = {
		name = 'Beater Dukes',
		brand = 'Imponte',
		model = 'dukes3',
		price = 120000,
		category = 'muscle',
		hash = `dukes3`,
	},
	euros = {
		name = 'Euros',
		brand = 'Annis',
		model = 'euros',
		price = 142000,
		category = 'tuner',
		hash = `euros`,
	},
	cheburek = {
		name = 'Cheburek',
		brand = 'RUNE',
		model = 'cheburek',
		price = 130000,
		category = 'sportsclassics',
		hash = `cheburek`,
	},
	feltzer3 = {
		name = 'Stirling GT',
		brand = 'Benefactor',
		model = 'feltzer3',
		price = 145000,
		category = 'sportsclassics',
		hash = `feltzer3`,
	},
	fugitive = {
		name = 'Fugitive',
		brand = 'Ceval',
		model = 'fugitive',
		price = 136000,
		category = 'sedans',
		hash = `fugitive`,
	},
	futo = {
		name = 'Futo',
		brand = 'Karin',
		model = 'futo',
		price = 110000,
		category = 'tuner',
		hash = `futo`,
	},
	futo2 = {
		name = 'Futo GTX',
		brand = 'Karin',
		model = 'futo2',
		price = 145000,
		category = 'tuner',
		hash = `futo2`,
	},
	gauntlet3 = {
		name = 'Gauntlet Classic',
		brand = 'Bravado',
		model = 'gauntlet3',
		price = 140000,
		category = 'muscle',
		hash = `gauntlet3`,
	},
	gauntlet5 = {
		name = 'Gauntlet Classic Custom',
		brand = 'Bravado',
		model = 'gauntlet5',
		price = 150000,
		category = 'muscle',
		hash = `gauntlet5`,
	},
	gt500 = {
		name = 'GT500',
		brand = 'Grotti',
		model = 'gt500',
		price = 125000,
		category = 'sportsclassics',
		hash = `gt500`,
	},
	hakuchou2 = {
		name = 'Hakuchou Drag',
		brand = 'Shitzu',
		model = 'hakuchou2',
		price = 118500,
		category = 'motorcycles',
		hash = `hakuchou2`,
	},
	issi7 = {
		name = 'Issi Sport',
		brand = 'Weeny',
		model = 'issi7',
		price = 110000,
		category = 'sports',
		hash = `issi7`,
	},
	jackal = {
		name = 'Jackal',
		brand = 'Ocelot',
		model = 'jackal',
		price = 121000,
		category = 'sedans',
		hash = `jackal`,
	},
	kanjo = {
		name = 'Blista Kanjo',
		brand = 'Dinka',
		model = 'kanjo',
		price = 110000,
		category = 'tuner',
		hash = `kanjo`,
	},
	kanjosj = {
		name = 'Blista Kanjo SJ',
		brand = 'Dinka',
		model = 'kanjosj',
		price = 125000,
		category = 'tuner',
		hash = `kanjosj`,
	},
	novak = {
		name = 'Novak',
		brand = 'Lampadati',
		model = 'novak',
		price = 127000,
		category = 'suvs',
		hash = `novak`,
	},
	omnis = {
		name = 'Omnis',
		brand = 'Obey',
		model = 'omnis',
		price = 145000,
		category = 'tuner',
		hash = `omnis`,
	},
	oracle = {
		name = 'Oracle',
		brand = 'Übermacht',
		model = 'oracle',
		price = 130000,
		category = 'sedans',
		hash = `oracle`,
	},
	oracle2 = {
		name = 'Oracle XS',
		brand = 'Übermacht',
		model = 'oracle2',
		price = 140000,
		category = 'sedans',
		hash = `oracle2`,
	},
	previon = {
		name = 'Previon',
		brand = 'Karin',
		model = 'previon',
		price = 115000,
		category = 'sports',
		hash = `previon`,
	},
	remus = {
		name = 'Remus',
		brand = 'Annis',
		model = 'remus',
		price = 148000,
		category = 'tuner',
		hash = `remus`,
	},
	retinue = {
		name = 'Retinue',
		brand = 'Vapid',
		model = 'retinue',
		price = 125000,
		category = 'sportsclassics',
		hash = `retinue`,
	},
	rt3000 = {
		name = 'RT3000',
		brand = 'Dinka',
		model = 'rt3000',
		price = 148000,
		category = 'tuner',
		hash = `rt3000`,
	},
	ruston = {
		name = 'Ruston',
		brand = 'Hijak',
		model = 'ruston',
		price = 100000,
		category = 'sports',
		hash = `ruston`,
	},
	sabregt = {
		name = 'Sabre Turbo',
		brand = 'Declasse',
		model = 'sabregt',
		price = 145000,
		category = 'muscle',
		hash = `sabregt`,
	},
	sadler = {
		name = 'Sadler',
		brand = 'Vapid',
		model = 'sadler',
		price = 122000,
		category = 'offroad',
		hash = `sadler`,
	},
	savestra = {
		name = 'Savestra',
		brand = 'Annis',
		model = 'savestra',
		price = 150000,
		category = 'sportsclassics',
		hash = `savestra`,
	},
	schafter2 = {
		name = 'Schafter',
		brand = 'Benefactor',
		model = 'schafter2',
		price = 128000,
		category = 'sedans',
		hash = `schafter2`,
	},
	schafter3 = {
		name = 'Schafter V12',
		brand = 'Benefactor',
		model = 'schafter3',
		price = 138000,
		category = 'sports',
		hash = `schafter3`,
	},
	sentinel3 = {
		name = 'Sentinel Classic',
		brand = 'Übermacht',
		model = 'sentinel3',
		price = 145000,
		category = 'tuner',
		hash = `sentinel3`,
	},
	sentinel4 = {
		name = 'Sentinel Classic WB',
		brand = 'Übermacht',
		model = 'sentinel4',
		price = 148000,
		category = 'tuner',
		hash = `sentinel4`,
	},
	shinobi = {
		name = 'Shinobi',
		brand = 'Nagasaki',
		model = 'shinobi',
		price = 139500,
		category = 'motorcycles',
		hash = `shinobi`,
	},
	slamvan = {
		name = 'Slamvan',
		brand = 'Vapid',
		model = 'slamvan',
		price = 135000,
		category = 'muscle',
		hash = `slamvan`,
	},
	stratum = {
		name = 'Stratum',
		brand = 'Zirconium',
		model = 'stratum',
		price = 149000,
		category = 'sedans',
		hash = `stratum`,
	},
	streiter = {
		name = 'Streiter',
		brand = 'Benefactor',
		model = 'streiter',
		price = 145000,
		category = 'suvs',
		hash = `streiter`,
	},
	sugoi = {
		name = 'Sugoi',
		brand = 'Dinka',
		model = 'sugoi',
		price = 126000,
		category = 'sports',
		hash = `sugoi`,
	},
	sultan = {
		name = 'Sultan',
		brand = 'Karin',
		model = 'sultan',
		price = 110000,
		category = 'sedans',
		hash = `sultan`,
	},
	tailgater = {
		name = 'Tailgater',
		brand = 'Obey',
		model = 'tailgater',
		price = 125000,
		category = 'sedans',
		hash = `tailgater`,
	},
	tampa = {
		name = 'Tampa',
		brand = 'Declasse',
		model = 'tampa',
		price = 120000,
		category = 'muscle',
		hash = `tampa`,
	},
	thrust = {
		name = 'Thrust',
		brand = 'Dinka',
		model = 'thrust',
		price = 114500,
		category = 'motorcycles',
		hash = `thrust`,
	},
	trophytruck = {
		name = 'Trophy Truck',
		brand = 'Vapid',
		model = 'trophytruck',
		price = 125000,
		category = 'tuner',
		hash = `trophytruck`,
	},
	trophytruck2 = {
		name = 'Trophy Truck Limited',
		brand = 'Vapid',
		model = 'trophytruck2',
		price = 140000,
		category = 'tuner',
		hash = `trophytruck2`,
	},
	vamos = {
		name = 'Vamos',
		brand = 'Declasse',
		model = 'vamos',
		price = 146000,
		category = 'muscle',
		hash = `vamos`,
	},
	windsor = {
		name = 'Windsor',
		brand = 'Enus',
		model = 'windsor',
		price = 127000,
		category = 'coupes',
		hash = `windsor`,
	},
	windsor2 = {
		name = 'Windsor Drop',
		brand = 'Enus',
		model = 'windsor2',
		price = 130000,
		category = 'sedans',
		hash = `windsor2`,
	},
	wolfsbane = {
		name = 'Wolfsbane',
		brand = 'WMC',
		model = 'wolfsbane',
		price = 116500,
		category = 'motorcycles',
		hash = `wolfsbane`,
	},
	yosemite3 = {
		name = 'Yosemite Racher',
		brand = 'Declasse',
		model = 'yosemite3',
		price = 135000,
		category = 'offroad',
		hash = `yosemite3`,
	},
	zr350 = {
		name = 'ZR-350',
		brand = 'Annis',
		model = 'zr350',
		price = 145000,
		category = 'tuner',
		hash = `zr350`,
	},
	--- A Class
	alpha = {
		name = 'Alpha',
		brand = 'Albany',
		model = 'alpha',
		price = 260000,
		category = 'sports',
		hash = `alpha`,
	},
	banshee = {
		name = 'Banshee',
		brand = 'Bravado',
		model = 'banshee',
		price = 275000,
		category = 'sports',
		hash = `banshee`,
	},
	bati = {
		name = 'Bati 801',
		brand = 'Pegassi',
		model = 'bati',
		price = 260000,
		category = 'motorcycles',
		hash = `bati`,
	},
	bestiagts = {
		name = 'Bestia GTS',
		brand = 'Grotti',
		model = 'bestiagts',
		price = 325000,
		category = 'sports',
		hash = `bestiagts`,
	},
	buffalo4 = {
		name = 'Buffalo STX',
		brand = 'Bravado',
		model = 'buffalo4',
		price = 295000,
		category = 'muscle',
		hash = `buffalo4`,
	},
	bullet = {
		name = 'Bullet',
		brand = 'Vapid',
		model = 'bullet',
		price = 300000,
		category = 'super',
		hash = `bullet`,
	},
	calico = {
		name = 'Calico GTF',
		brand = 'Karin',
		model = 'calico',
		price = 262000,
		category = 'tuner',
		hash = `calico`,
	},
	carbonizzare = {
		name = 'Carbonizzare',
		brand = 'Grotti',
		model = 'carbonizzare',
		price = 285000,
		category = 'sports',
		hash = `carbonizzare`,
	},
	carbonrs = {
		name = 'Carbon RS',
		brand = 'Nagasaki',
		model = 'carbonrs',
		price = 255000,
		category = 'motorcycles',
		hash = `carbonrs`,
	},
	champion = {
		name = 'Champion',
		brand = 'Dewbauchee',
		model = 'champion',
		price = 300000,
		category = 'super',
		hash = `champion`,
	},
	cheetah2 = {
		name = 'Cheetah Classic',
		brand = 'Grotti',
		model = 'cheetah2',
		price = 300000,
		category = 'sportsclassics',
		hash = `cheetah2`,
	},
	comet5 = {
		name = 'Comet SR',
		brand = 'Phister',
		model = 'comet5',
		price = 270000,
		category = 'sports',
		hash = `comet5`,
	},
	coquette = {
		name = 'Coquette',
		brand = 'Invetero',
		model = 'coquette',
		price = 275000,
		category = 'sports',
		hash = `coquette`,
	},
	coquette2 = {
		name = 'Coquette Classic',
		brand = 'Invetero',
		model = 'coquette2',
		price = 255000,
		category = 'sportsclassics',
		hash = `coquette2`,
	},
	corsita = {
		name = 'Corsita',
		brand = 'Lampadati',
		model = 'corsita',
		price = 300000,
		category = 'super',
		hash = `corsita`,
	},
	cypher = {
		name = 'Cypher',
		brand = 'Übermacht',
		model = 'cypher',
		price = 257000,
		category = 'sports',
		hash = `cypher`,
	},
	dominator3 = {
		name = 'Dominator GTX',
		brand = 'Vapid',
		model = 'dominator3',
		price = 295000,
		category = 'sports',
		hash = `dominator3`,
	},
	dominator7 = {
		name = 'Dominator ASP',
		brand = 'Vapid',
		model = 'dominator7',
		price = 260000,
		category = 'muscle',
		hash = `dominator7`,
	},
	drafter = {
		name = '8F Drafter',
		brand = 'Obey',
		model = 'drafter',
		price = 295000,
		category = 'sports',
		hash = `drafter`,
	},
	elegy2 = {
		name = 'Elegy RH8',
		brand = 'Annis',
		model = 'elegy2',
		price = 295000,
		category = 'tuner',
		hash = `elegy2`,
	},
	ellie = {
		name = 'Ellie',
		brand = 'Vapid',
		model = 'ellie',
		price = 295000,
		category = 'muscle',
		hash = `ellie`,
	},
	feltzer2 = {
		name = 'Feltzer',
		brand = 'Benefactor',
		model = 'feltzer2',
		price = 270000,
		category = 'sports',
		hash = `feltzer2`,
	},
	flashgt = {
		name = 'Flash GT',
		brand = 'Vapid',
		model = 'flashgt',
		price = 265000,
		category = 'tuner',
		hash = `flashgt`,
	},
	furoregt = {
		name = 'Furore GT',
		brand = 'Lampadati',
		model = 'furoregt',
		price = 275000,
		category = 'sports',
		hash = `furoregt`,
	},
	gauntlet = {
		name = 'Gauntlet',
		brand = 'Bravado',
		model = 'gauntlet',
		price = 280000,
		category = 'muscle',
		hash = `gauntlet`,
	},
	gb200 = {
		name = 'GB200',
		brand = 'Vapid',
		model = 'gb200',
		price = 275000,
		category = 'tuner',
		hash = `gb200`,
	},
	growler = {
		name = 'Growler',
		brand = 'Pfister',
		model = 'growler',
		price = 276000,
		category = 'super',
		hash = `growler`,
	},
	hotknife = {
		name = 'Hotring Sabre',
		brand = 'Declasse',
		model = 'hotknife',
		price = 285000,
		category = 'tuner',
		hash = `hotknife`,
	},
	infernus = {
		name = 'Infernus',
		brand = 'Pegassi',
		model = 'infernus',
		price = 275000,
		category = 'super',
		hash = `infernus`,
	},
	italigto = {
		name = 'Itali GTO',
		brand = 'Grotti',
		model = 'italigto',
		price = 300000,
		category = 'super',
		hash = `italigto`,
	},
	jester = {
		name = 'Jester',
		brand = 'Dinka',
		model = 'jester',
		price = 275000,
		category = 'tuner',
		hash = `jester`,
	},
	jester3 = {
		name = 'Jester Classic',
		brand = 'Dinka',
		model = 'jester3',
		price = 285000,
		category = 'tuner',
		hash = `jester3`,
	},
	jester4 = {
		name = 'Jester RR',
		brand = 'Dinka',
		model = 'jester4',
		price = 295000,
		category = 'tuner',
		hash = `jester4`,
	},
	jugular = {
		name = 'Jugular',
		brand = 'Ocelot',
		model = 'jugular',
		price = 295000,
		category = 'sports',
		hash = `jugular`,
	},
	komoda = {
		name = 'Komoda',
		brand = 'Lampadati',
		model = 'komoda',
		price = 300000,
		category = 'sports',
		hash = `komoda`,
	},
	le7b = {
		name = 'RE-7B',
		brand = 'Annis',
		model = 'le7b',
		price = 300000,
		category = 'tuner',
		hash = `le7b`,
	},
	lynx = {
		name = 'Lynx',
		brand = 'Ocelot',
		model = 'lynx',
		price = 275000,
		category = 'sports',
		hash = `lynx`,
	},
	mamba = {
		name = 'Mamba',
		brand = 'Declasse',
		model = 'mamba',
		price = 281000,
		category = 'sports',
		hash = `mamba`,
	},
	massacro = {
		name = 'Massacro',
		brand = 'Dewbauchee',
		model = 'massacro',
		price = 265000,
		category = 'sports',
		hash = `massacro`,
	},
	nightshade = {
		name = 'Nightshade',
		brand = 'Imponte',
		model = 'nightshade',
		price = 278000,
		category = 'muscle',
		hash = `nightshade`,
	},
	ninef = {
		name = '9F',
		brand = 'Obey',
		model = 'ninef',
		price = 285000,
		category = 'sports',
		hash = `ninef`,
	},
	ninef2 = {
		name = '9F Cabrio',
		brand = 'Obey',
		model = 'ninef2',
		price = 295000,
		category = 'sports',
		hash = `ninef2`,
	},
	paragon = {
		name = 'Paragon R',
		brand = 'Enus',
		model = 'paragon',
		price = 275000,
		category = 'super',
		hash = `paragon`,
	},
	pariah = {
		name = 'Pariah',
		brand = 'Ocelot',
		model = 'pariah',
		price = 275000,
		category = 'sports',
		hash = `pariah`,
	},
	pcj = {
		name = 'PCJ-600',
		brand = 'Shitzu',
		model = 'pcj',
		price = 275500,
		category = 'motorcycles',
		hash = `pcj`,
	},
	penumbra2 = {
		name = 'Penumbra FF',
		brand = 'Maibatsu',
		model = 'penumbra2',
		price = 275000,
		category = 'tuner',
		hash = `penumbra2`,
	},
	rapidgt = {
		name = 'Rapid GT',
		brand = 'Dewbauchee',
		model = 'rapidgt',
		price = 290000,
		category = 'sports',
		hash = `rapidgt`,
	},
	rapidgt2 = {
		name = 'Rapid GT Convertible',
		brand = 'Dewbauchee',
		model = 'rapidgt2',
		price = 292000,
		category = 'sports',
		hash = `rapidgt2`,
	},
	rapidgt3 = {
		name = 'Rapid GT Classic',
		brand = 'Dewbauchee',
		model = 'rapidgt3',
		price = 280000,
		category = 'sportsclassics',
		hash = `rapidgt3`,
	},
	reaper = {
		name = 'Reaper',
		brand = 'Pegassi',
		model = 'reaper',
		price = 290000,
		category = 'super',
		hash = `reaper`,
	},
	ruiner = {
		name = 'Ruiner',
		brand = 'Imponte',
		model = 'ruiner',
		price = 250000,
		category = 'muscle',
		hash = `ruiner`,
	},
	ruiner4 = {
		name = 'Ruiner ZZ-8',
		brand = 'Imponte',
		model = 'ruiner4',
		price = 285000,
		category = 'muscle',
		hash = `ruiner4`,
	},
	sabregt2 = {
		name = 'Sabre GT',
		brand = 'Declasse',
		model = 'sabregt2',
		price = 255000,
		category = 'muscle',
		hash = `sabregt2`,
	},
	schwarzer = {
		name = 'Schwartzer',
		brand = 'Benefactor',
		model = 'schwarzer',
		price = 290000,
		category = 'sports',
		hash = `schwarzer`,
	},
	sentinel = {
		name = 'Sentinel XS',
		brand = 'Übermacht',
		model = 'sentinel',
		price = 276500,
		category = 'coupes',
		hash = `sentinel`,
	},
	sentinel2 = {
		name = 'Sentinel',
		brand = 'Übermacht',
		model = 'sentinel2',
		price = 275000,
		category = 'coupes',
		hash = `sentinel2`,
	},
	seven70 = {
		name = 'Seven-70',
		brand = 'Dewbauchee',
		model = 'seven70',
		price = 265000,
		category = 'sports',
		hash = `seven70`,
	},
	sheava = {
		name = 'ETR1',
		brand = 'Emperor',
		model = 'sheava',
		price = 260000,
		category = 'tuner',
		hash = `sheava`,
	},
	specter = {
		name = 'Specter',
		brand = 'Dewbauchee',
		model = 'specter',
		price = 285000,
		category = 'sports',
		hash = `specter`,
	},
	specter2 = {
		name = 'Specter Custom',
		brand = 'Dewbauchee',
		model = 'specter2',
		price = 295000,
		category = 'sports',
		hash = `specter2`,
	},
	sultan2 = {
		name = 'Sultan Classic',
		brand = 'Karin',
		model = 'sultan2',
		price = 295000,
		category = 'tuner',
		hash = `sultan2`,
	},
	sultan3 = {
		name = 'Sultan RS Classic',
		brand = 'Karin',
		model = 'sultan3',
		price = 283000,
		category = 'tuner',
		hash = `sultan3`,
	},
	sultanrs = {
		name = 'Sultan RS',
		brand = 'Karin',
		model = 'sultanrs',
		price = 300000,
		category = 'tuner',
		hash = `sultanrs`,
	},
	sultan2c = {
		name = 'Sultan Classic Custom',
		brand = 'Karin',
		model = 'sultan2c',
		price = 297000,
		category = 'tuner',
		hash = `sultan2c`,
	},
	surano = {
		name = 'Surano',
		brand = 'Benefactor',
		model = 'surano',
		price = 285000,
		category = 'sports',
		hash = `surano`,
	},
	tailgater2 = {
		name = 'Tailgater S',
		brand = 'Obey',
		model = 'tailgater2',
		price = 275000,
		category = 'tuner',
		hash = `tailgater2`,
	},
	toros = {
		name = 'Toros',
		brand = 'Pegassi',
		model = 'toros',
		price = 285000,
		category = 'suvs',
		hash = `toros`,
	},
	tropos = {
		name = 'Tropos Rallye',
		brand = 'Lampadati',
		model = 'tropos',
		price = 260000,
		category = 'tuner',
		hash = `tropos`,
	},
	vectre = {
		name = 'Vectre',
		brand = 'Emperor',
		model = 'vectre',
		price = 285000,
		category = 'super',
		hash = `vectre`,
	},
	verlierer2 = {
		name = 'Verlierer',
		brand = 'Bravado',
		model = 'verlierer2',
		price = 290000,
		category = 'sports',
		hash = `verlierer2`,
	},
	vigero2 = {
		name = 'Vigero ZX',
		brand = 'Declasse',
		model = 'vigero2',
		price = 284000,
		category = 'muscle',
		hash = `vigero2`,
	},
	vstr = {
		name = 'V-STR',
		brand = 'Albany',
		model = 'vstr',
		price = 295000,
		category = 'sports',
		hash = `vstr`,
	},
	yosemite = {
		name = 'Yosemite',
		brand = 'Declasse',
		model = 'yosemite',
		price = 288000,
		category = 'muscle',
		hash = `yosemite`,
	},
	--- S Class
	adder = {
		name = 'Adder',
		brand = 'Truffade',
		model = 'adder',
		price = 580000,
		category = 'super',
		hash = `adder`,
	},
	banshee2 = {
		name = 'Banshee 900R',
		brand = 'Bravado',
		model = 'banshee2',
		price = 475000,
		category = 'sports',
		hash = `banshee2`,
	},
	cheetah = {
		name = 'Cheetah',
		brand = 'Grotti',
		model = 'cheetah',
		price = 550000,
		category = 'super',
		hash = `cheetah`,
	},
	comet6 = {
		name = 'Comet S2',
		brand = 'Phister',
		model = 'comet6',
		price = 460000,
		category = 'super',
		hash = `comet6`,
	},
	comet7 = {
		name = 'Comet S2 Cabrio',
		brand = 'Phister',
		model = 'comet7',
		price = 510000,
		category = 'super',
		hash = `comet7`,
	},
	coquette4 = {
		name = 'Coquette D10',
		brand = 'Invetero',
		model = 'coquette4',
		price = 510000,
		category = 'super',
		hash = `coquette4`,
	},
	furia = {
		name = 'Furia',
		brand = 'Grotti',
		model = 'furia',
		price = 575000,
		category = 'super',
		hash = `furia`,
	},
	gauntlet4 = {
		name = 'Gauntlet Hellfire',
		brand = 'Bravado',
		model = 'gauntlet4',
		price = 480000,
		category = 'muscle',
		hash = `namgauntlet4e1`,
	},
	gp1 = {
		name = 'GP1',
		brand = 'Progen',
		model = 'gp1',
		price = 575000,
		category = 'super',
		hash = `gp1`,
	},
	infernus2 = {
		name = 'Infernus Classic',
		brand = 'Pegassi',
		model = 'infernus2',
		price = 415000,
		category = 'super',
		hash = `infernus2`,
	},
	italigtb = {
		name = 'Itali GTB',
		brand = 'Grotti',
		model = 'italigtb',
		price = 465000,
		category = 'super',
		hash = `italigtb`,
	},
	italigtb2 = {
		name = 'Itali GTB Custom',
		brand = 'Grotti',
		model = 'italigtb2',
		price = 485000,
		category = 'tuner',
		hash = `italigtb2`,
	},
	nero = {
		name = 'Nero',
		brand = 'Truffade',
		model = 'nero',
		price = 530000,
		category = 'tuner',
		hash = `nero`,
	},
	osiris = {
		name = 'Osiris',
		brand = 'Pegassi',
		model = 'osiris',
		price = 550000,
		category = 'super',
		hash = `osiris`,
	},
	penetrator = {
		name = 'Penetrator',
		brand = 'Ocelot',
		model = 'penetrator',
		price = 425000,
		category = 'super',
		hash = `penetrator`,
	},
	pfister811 = {
		name = '811',
		brand = 'Pfister',
		model = 'pfister811',
		price = 485000,
		category = 'super',
		hash = `pfister811`,
	},
	sc1 = {
		name = 'SC1',
		brand = 'Übermacht',
		model = 'sc1',
		price = 550000,
		category = 'super',
		hash = `sc1`,
	},
	t20 = {
		name = 'T20',
		brand = 'Progen',
		model = 't20',
		price = 600000,
		category = 'super',
		hash = `t20`,
	},
	tempesta = {
		name = 'Tempesta',
		brand = 'Pegassi',
		model = 'tempesta',
		price = 520000,
		category = 'super',
		hash = `tempesta`,
	},
	tenf = {
		name = '10F',
		brand = 'Obey',
		model = 'tenf',
		price = 520000,
		category = 'super',
		hash = `tenf`,
	},
	tenf2 = {
		name = '10F Widebody',
		brand = 'Obey',
		model = 'tenf2',
		price = 540000,
		category = 'tuner',
		hash = `tenf2`,
	},
	turismo2 = {
		name = 'Turismo Classic',
		brand = 'Grotti',
		model = 'turismo2',
		price = 420000,
		category = 'tuner',
		hash = `turismo2`,
	},
	turismor = {
		name = 'Turismo R',
		brand = 'Grotti',
		model = 'turismor',
		price = 440000,
		category = 'super',
		hash = `turismor`,
	},
	vacca = {
		name = 'Vacca',
		brand = 'Pegassi',
		model = 'vacca',
		price = 550000,
		category = 'super',
		hash = `vacca`,
	},
	xa21 = {
		name = 'XA-21',
		brand = 'Ocelot',
		model = 'xa21',
		price = 429000,
		category = 'super',
		hash = `xa21`,
	},
	elegyh = {
		name = 'Elegy RH-5 Heritage',
		brand = 'Annis',
		model = 'elegyh',
		price = 600000,
		category = 'tuner',
		hash = `elegyh`,
	},
	elegyrh7 = {
		name = 'Elegy RH-7',
		brand = 'Annis',
		model = 'elegyrh7',
		price = 590000,
		category = 'tuner',
		hash = `elegyrh7`,
	},
	sultanrsv8 = {
		name = 'Sultan RS V8',
		brand = 'Karin',
		model = 'sultanrsv8',
		price = 525000,
		category = 'tuner',
		hash = `sultanrsv8`,
	},
	--- X Class
	autarch = {
		name = 'Autarch',
		brand = 'Överflöd',
		model = 'autarch',
		price = 1100000,
		category = 'super',
		hash = `autarch`,
	},
	entity2 = {
		name = 'Entity XXR',
		brand = 'Överflöd',
		model = 'entity2',
		price = 1500000,
		category = 'super',
		hash = `entity2`,
	},
	entityxf = {
		name = 'Entity XF',
		brand = 'Överflöd',
		model = 'entityxf',
		price = 1300000,
		category = 'super',
		hash = `entityxf`,
	},
	italirsx = {
		name = 'Itali RSX',
		brand = 'Grotti',
		model = 'italirsx',
		price = 1200000,
		category = 'super',
		hash = `italirsx`,
	},
	nero2 = {
		name = 'Nero Custom',
		brand = 'Truffade',
		model = 'nero2',
		price = 1600000,
		category = 'super',
		hash = `nero2`,
	},
	prototipo = {
		name = 'X80 Proto',
		brand = 'Grotti',
		model = 'prototipo',
		price = 1800000,
		category = 'super',
		hash = `prototipo`,
	},
	sm722 = {
		name = 'SM722',
		brand = 'Benefactor',
		model = 'sm722',
		price = 1170000,
		category = 'super',
		hash = `sm722`,
	},
	taipan = {
		name = 'Taipan',
		brand = 'Cheval',
		model = 'taipan',
		price = 1250000,
		category = 'super',
		hash = `taipan`,
	},
	torero2 = {
		name = 'Torero XO',
		brand = 'Pegassi',
		model = 'torero2',
		price = 1150000,
		category = 'super',
		hash = `torero2`,
	},
	tyrant = {
		name = 'Tyrant',
		brand = 'Överflöd',
		model = 'tyrant',
		price = 950000,
		category = 'super',
		hash = `tyrant`,
	},
	fmj = {
		name = 'FMJ',
		brand = 'Vapid',
		model = 'fmj',
		price = 1200000,
		category = 'super',
		hash = `fmj`,
	},
	visione = {
		name = 'Visione',
		brand = 'Grotti',
		model = 'visione',
		price = 1000000,
		category = 'super',
		hash = `visione`,
	},
	vagner = {
		name = 'Vagner',
		brand = 'Dewbauchee',
		model = 'vagner',
		price = 900000,
		category = 'super',
		hash = `vagner`,
	},
	--- DLC Cars (mpchristmas)
	entity3 = {
		name = 'Entity MT',
		brand = 'Överflöd',
		model = 'entity3',
		price = 1270000,
		category = 'super',
		hash = `entity3`,
	},
	r300 = {
		name = '300R',
		brand = 'Annis',
		model = 'r300',
		price = 290000,
		category = 'tuner',
		hash = `r300`,
	},
	panthere = {
		name = 'Panthere',
		brand = 'Toundra',
		model = 'panthere',
		price = 285000,
		category = 'tuner',
		hash = `panthere`,
	},
	issi8 = {
		name = 'Issi Rally',
		brand = 'Weeny',
		model = 'issi8',
		price = 125000,
		category = 'tuner',
		hash = `issi8`,
	},
	boor = {
		name = 'Boor',
		brand = 'Karin',
		model = 'boor',
		price = 130000,
		category = 'sportsclassics',
		hash = `boor`,
	},
	broadway = {
		name = 'Broadway',
		brand = 'Classique',
		model = 'broadway',
		price = 13000,
		category = 'muscle',
		hash = `broadway`,
	},
	eudora = {
		name = 'Eudora',
		brand = 'Willard',
		model = 'eudora',
		price = 3100,
		category = 'lowincome',
		hash = `eudora`,
	},
	journey2 = {
		name = 'Journey II',
		brand = 'Zirconium',
		model = 'journey2',
		price = 24000,
		category = 'utility',
		hash = `journey2`,
	},
	manchez3 = {
		name = 'Manchez Scout C',
		brand = 'Maibatsu',
		model = 'manchez3',
		price = 17000,
		category = 'motorcycles',
		hash = `manchez3`,
	},
	surfer3 = {
		name = 'Surfer Custom',
		brand = 'BF',
		model = 'surfer3',
		price = 9000,
		category = 'vans',
		hash = `surfer3`,
	},
	tahoma = {
		name = 'Tahoma Coupe',
		brand = 'Declasse',
		model = 'tahoma',
		price = 2000,
		category = 'lowincome',
		hash = `tahoma`,
	},
	tulip2 = {
		name = 'Tulip M-100',
		brand = 'Declasse',
		model = 'tulip2',
		price = 2400,
		category = 'lowincome',
		hash = `tulip2`,
	},
	--- Imports (Feb, Mar, Jul, Aug)
	templar = {
		name = 'Templar',
		brand = 'LCC',
		model = 'templar',
		price = 140000,
		category = 'motorcycles',
		hash = `templar`,
	},
	kawaii = {
		name = 'Kawaii',
		brand = 'Annis',
		model = 'kawaii',
		price = 116500,
		category = 'tuner',
		hash = `kawaii`,
	},
	zr250 = {
		name = 'ZR-250',
		brand = 'Annis',
		model = 'zr250',
		price = 123500,
		category = 'tuner',
		hash = `zr250`,
	},
	vincent2 = {
		name = 'Vincent Sport',
		brand = 'Maibatsu',
		model = 'vincent2',
		price = 145500,
		category = 'tuner',
		hash = `vincent2`,
	},
	vincent3 = {
		name = 'Vincent Tourer',
		brand = 'Maibatsu',
		model = 'vincent3',
		price = 150000,
		category = 'tuner',
		hash = `vincent3`,
	},
	cypherct = {
		name = 'Cypher Hatchback',
		brand = 'Übermacht',
		model = 'cypherct',
		price = 125000,
		category = 'compacts',
		hash = `cypherct`,
	},
	hellion2 = {
		name = 'Hellion XL',
		brand = 'Annis',
		model = 'hellion2',
		price = 105000,
		category = 'offroad',
		hash = `hellion2`,
	},
	mesaxl = {
		name = 'Gator 4x4',
		brand = 'Canis',
		model = 'mesaxl',
		price = 140000,
		category = 'offroad',
		hash = `mesaxl`,
	},
	mesar = {
		name = 'Mesa R',
		brand = 'Canis',
		model = 'mesar',
		price = 135500,
		category = 'offroad',
		hash = `mesar`,
	},
	scheisser = {
		name = 'Scheisser',
		brand = 'Benefactor',
		model = 'scheisser',
		price = 140500,
		category = 'sedans',
		hash = `scheisser`,
	},
	ferocid = {
		name = 'Feroci Custom',
		brand = 'Bravado',
		model = 'ferocid',
		price = 139000,
		category = 'tuner',
		hash = `ferocid`,
	},
	lowriderb = {
		name = 'Lowrider Bicycle',
		brand = ' ',
		model = 'lowriderb',
		price = 1200,
		category = 'cycles',
		hash = `lowriderb`,
	},
	dukesd = {
		name = 'Hotring Dukes',
		brand = 'Imponte',
		model = 'dukesd',
		price = 290000,
		category = 'muscle',
		hash = `dukesd`,
	},
	rh4 = {
		name = 'Elegy RH4',
		brand = 'Annis',
		model = 'rh4',
		price = 285000,
		category = 'tuner',
		hash = `rh4`,
	},
	komodafr = {
		name = 'Komoda FR-Works',
		brand = 'Lampadati',
		model = 'komodafr',
		price = 285000,
		category = 'tuner',
		hash = `komodafr`,
	},
	s230 = {
		name = 'S-230',
		brand = 'Annis',
		model = 's230',
		price = 275000,
		category = 'tuner',
		hash = `s230`,
	},
	sentinelsg4 = {
		name = 'Sentinel SG4',
		brand = 'Übermacht',
		model = 'sentinelsg4',
		price = 295000,
		category = 'sports',
		hash = `sentinelsg4`,
	},
	stratumc = {
		name = 'Stratum WB',
		brand = 'Zircoflow',
		model = 'stratumc',
		price = 280000,
		category = 'sports',
		hash = `stratumc`,
	},
	sunrise1 = {
		name = 'Sunrise R',
		brand = 'Maibatsu',
		model = 'sunrise1',
		price = 299000,
		category = 'tuner',
		hash = `sunrise1`,
	},
	vorstand = {
		name = 'Vorstand',
		brand = 'Übermacht',
		model = 'vorstand',
		price = 265000,
		category = 'tuner',
		hash = `vorstand`,
	},
	nexus = {
		name = 'Nexus Classic',
		brand = 'Dinka',
		model = 'nexus',
		price = 265000,
		category = 'tuner',
		hash = `nexus`,
	},
	zion4 = {
		name = 'Zion Classic Custom',
		brand = 'Übermacht',
		model = 'zion4',
		price = 255000,
		category = 'sportsclassics',
		hash = `zion4`,
	},
	schlagenstr = {
		name = 'Schlagen STR',
		brand = 'Benefactor',
		model = 'schlagenstr',
		price = 600000,
		category = 'super',
		hash = `schlagenstr`,
	},
	citi = {
		name = 'City',
		brand = 'Dinka',
		model = 'citi',
		price = 255000,
		category = 'sports',
		hash = `citi`,
	},
	tempestaes = {
		name = 'Tempesta Evo Stradale',
		brand = 'Pegassi',
		model = 'tempestaes',
		price = 580000,
		category = 'super',
		hash = `tempestaes`,
	},
	turismoc = {
		name = 'Turismo Classic Custom',
		brand = 'Grotti',
		model = 'turismoc',
		price = 599000,
		category = 'super',
		hash = `turismoc`,
	},
	tt750 = {
		name = 'TT 750',
		brand = 'Dinka',
		model = 'tt750',
		price = 265000,
		category = 'motorcycles',
		hash = `tt750`,
	},
	yosemitedrt = {
		name = 'Yosemite DRT',
		brand = 'Declasse',
		model = 'yosemitedrt',
		price = 285000,
		category = 'tuner',
		hash = `yosemitedrt`,
	},
	doubled = {
		name = 'DD-BLITZ',
		brand = 'Obey',
		model = 'doubled',
		price = 295000,
		category = 'tuner',
		hash = `doubled`,
	},
	paragonxr = {
		name = 'Paragon FR-Works',
		brand = 'Enus',
		model = 'paragonxr',
		price = 650000,
		category = 'tuner',
		hash = `paragonxr`,
	},
	ruinerafd = {
		name = 'Ruiner UTE',
		brand = 'Imponte',
		model = 'ruinerafd',
		price = 490000,
		category = 'sportsclassics',
		hash = `ruinerafd`,
	},
	jackgpr = {
		name = 'Jackal Custom',
		brand = 'Ocelot',
		model = 'jackgpr',
		price = 285000,
		category = 'tuner',
		hash = `jackgpr`,
	},
	jdvigeror = {
		name = 'Vigero Rumbler',
		brand = 'Declasse',
		model = 'jdvigeror',
		price = 585000,
		category = 'muscle',
		hash = `jdvigeror`,
	},
	jestgpr = {
		name = 'Jester re-RR',
		brand = 'Dinka',
		model = 'jestgpr',
		price = 585000,
		category = 'tuner',
		hash = `jestgpr`,
	},
	roxanne = {
		name = 'Roxanne',
		brand = 'Annis',
		model = 'roxanne',
		price = 575000,
		category = 'tuner',
		hash = `roxanne`,
	},
	lynxgpr = {
		name = 'Lynx Custom',
		brand = 'Ocelot',
		model = 'lynxgpr',
		price = 595000,
		category = 'tuner',
		hash = `lynxgpr`,
	},
	buffalo4h = {
		name = 'Buffalo Hellfire',
		brand = 'Bravado',
		model = 'buffalo4h',
		price = 280000,
		category = 'sports',
		hash = `buffalo4h`,
	},
	reagpr = {
		name = 'Reaper Custom',
		brand = 'Pegassi',
		model = 'reagpr',
		price = 599000,
		category = 'tuner',
		hash = `reagpr`,
	},
	schwarzer2 = {
		name = 'Schwartzer Custom',
		brand = 'Benefactor',
		model = 'schwarzer2',
		price = 565000,
		category = 'tuner',
		hash = `schwarzer2`,
	},
	velox = {
		name = 'Velox',
		brand = 'Schyster',
		model = 'velox',
		price = 565000,
		category = 'muscle',
		hash = `velox`,
	},
	--- Gang Cars
	requiemzr3 = {
		name = 'Requiem ZR',
		brand = 'Annis',
		model = 'requiemzr3',
		price = 275000,
		category = 'gang',
		hash = `requiemzr3`,
	},
	anarchy = {
		name = 'Anarchy',
		brand = 'WMC',
		model = 'anarchy',
		price = 155000,
		category = 'gang',
		hash = `anarchy`,
	},
	sentinelxs = {
		name = 'Sentinel XS',
		brand = 'Übermacht',
		model = 'sentinelxs',
		price = 265000,
		category = 'gang',
		hash = `sentinelxs`,
	},
	krust = {
		name = 'Krust',
		brand = 'LLC',
		model = 'krust',
		price = 55000,
		category = 'gang',
		hash = `krust`,
	},
	panorama = {
		name = 'Panorama',
		brand = 'Classique',
		model = 'panorama',
		price = 165000,
		category = 'gang',
		hash = `panorama`,
	},
	--- Boats
	dinghy = {
		name = 'Dinghy 4Seat',
		brand = ' ',
		model = 'dinghy',
		price = 15000,
		category = 'boats',
		hash = `dinghy`,
	},
	dinghy2 = {
		name = 'Dinghy 2Seat',
		brand = ' ',
		model = 'dinghy2',
		price = 10000,
		category = 'boats',
		hash = `dinghy2`,
	},
	dinghy4 = {
		name = 'Dinghy Yacht',
		brand = ' ',
		model = 'dinghy4',
		price = 20000,
		category = 'boats',
		hash = `dinghy4`,
	},
	jetmax = {
		name = 'Jetmax',
		brand = ' ',
		model = 'jetmax',
		price = 30000,
		category = 'boats',
		hash = `jetmax`,
	},
	marquis = {
		name = 'Marquis',
		brand = ' ',
		model = 'marquis',
		price = 45000,
		category = 'boats',
		hash = `marquis`,
	},
	seashark = {
		name = 'Seashark',
		brand = ' ',
		model = 'seashark',
		price = 4000,
		category = 'boats',
		hash = `seashark`,
	},
	seashark3 = {
		name = 'Seashark Yacht',
		brand = ' ',
		model = 'seashark3',
		price = 8000,
		category = 'boats',
		hash = `seashark3`,
	},
	speeder = {
		name = 'Speeder',
		brand = ' ',
		model = 'speeder',
		price = 40000,
		category = 'boats',
		hash = `speeder`,
	},
	squalo = {
		name = 'Squalo',
		brand = ' ',
		model = 'squalo',
		price = 32000,
		category = 'boats',
		hash = `squalo`,
	},
	submersible = {
		name = 'Submarine',
		brand = ' ',
		model = 'submersible',
		price = 400000,
		category = 'boats',
		hash = `submersible`,
	},
	submersible2 = {
		name = 'Kraken',
		brand = ' ',
		model = 'submersible2',
		price = 420000,
		category = 'boats',
		hash = `submersible2`,
	},
	toro = {
		name = 'Toro',
		brand = ' ',
		model = 'toro',
		price = 38000,
		category = 'boats',
		hash = `toro`,
	},
	toro2 = {
		name = 'Toro Yacht',
		brand = ' ',
		model = 'toro2',
		price = 38000,
		category = 'boats',
		hash = `toro2`,
	},
	tropic = {
		name = 'Tropic',
		brand = ' ',
		model = 'tropic',
		price = 27000,
		category = 'boats',
		hash = `tropic`,
	},
	tropic2 = {
		name = 'Tropic Yacht',
		brand = ' ',
		model = 'tropic2',
		price = 27000,
		category = 'boats',
		hash = `tropic2`,
	},
	longfin = {
		name = 'Longfin',
		brand = ' ',
		model = 'longfin',
		price = 85000,
		category = 'boats',
		hash = `longfin`,
	},
	--- Air
	alphaz1 = {
		name = 'Alpha Z1',
		brand = ' ',
		model = 'alphaz1',
		price = 1121000,
		category = 'planes',
		hash = `alphaz1`,
	},
	besra = {
		name = 'Besra',
		brand = ' ',
		model = 'besra',
		price = 1000000,
		category = 'planes',
		hash = `besra`,
	},
	alphaz1 = {
		name = 'Alpha Z1',
		brand = ' ',
		model = 'alphaz1',
		price = 1121000,
		category = 'planes',
		hash = `alphaz1`,
	},
	cuban800 = {
		name = 'Cuban 800',
		brand = ' ',
		model = 'cuban800',
		price = 240000,
		category = 'planes',
		hash = `cuban800`,
	},
	dodo = {
		name = 'Dodo',
		brand = ' ',
		model = 'dodo',
		price = 300000,
		category = 'planes',
		hash = `dodo`,
	},
	duster = {
		name = 'Duster',
		brand = ' ',
		model = 'duster',
		price = 125000,
		category = 'planes',
		hash = `duster`,
	},
	howard = {
		name = 'Howard NX25',
		brand = ' ',
		model = 'howard',
		price = 575000,
		category = 'planes',
		hash = `howard`,
	},
	luxor = {
		name = 'Luxor',
		brand = ' ',
		model = 'luxor',
		price = 1500000,
		category = 'planes',
		hash = `luxor`,
	},
	luxor2 = {
		name = 'Luxor Deluxe',
		brand = ' ',
		model = 'luxor2',
		price = 1750000,
		category = 'planes',
		hash = `luxor2`,
	},
	mammatus = {
		name = 'Mammatus',
		brand = ' ',
		model = 'mammatus',
		price = 300000,
		category = 'planes',
		hash = `mammatus`,
	},
	microlight = {
		name = 'Ultra Light',
		brand = ' ',
		model = 'microlight',
		price = 50000,
		category = 'planes',
		hash = `microlight`,
	},
	nimbus = {
		name = 'Nimbus',
		brand = ' ',
		model = 'nimbus',
		price = 750000,
		category = 'planes',
		hash = `nimbus`,
	},
	rogue = {
		name = 'Rogue',
		brand = ' ',
		model = 'rogue',
		price = 650000,
		category = 'planes',
		hash = `rogue`,
	},
	seabreeze = {
		name = 'Sea Breeze',
		brand = ' ',
		model = 'seabreeze',
		price = 600000,
		category = 'planes',
		hash = `seabreeze`,
	},
	shamal = {
		name = 'Shamal',
		brand = ' ',
		model = 'shamal',
		price = 1150000,
		category = 'planes',
		hash = `shamal`,
	},
	stunt = {
		name = 'Mallard',
		brand = ' ',
		model = 'stunt',
		price = 250000,
		category = 'planes',
		hash = `stunt`,
	},
	velum2 = {
		name = 'Velum',
		brand = ' ',
		model = 'velum2',
		price = 450000,
		category = 'planes',
		hash = `velum2`,
	},
	vestra = {
		name = 'Vestra',
		brand = ' ',
		model = 'vestra',
		price = 650000,
		category = 'planes',
		hash = `vestra`,
	},
	buzzard2 = {
		name = 'Buzzard',
		brand = ' ',
		model = 'buzzard2',
		price = 500000,
		category = 'helicopters',
		hash = `buzzard2`,
	},
	frogger = {
		name = 'Frogger',
		brand = ' ',
		model = 'frogger',
		price = 400000,
		category = 'helicopters',
		hash = `frogger`,
	},
	havok = {
		name = 'Havok',
		brand = ' ',
		model = 'havok',
		price = 125000,
		category = 'helicopters',
		hash = `havok`,
	},
	maverick = {
		name = 'Maverick',
		brand = ' ',
		model = 'maverick',
		price = 250000,
		category = 'helicopters',
		hash = `maverick`,
	},
	seasparrow = {
		name = 'Sea Sparrow',
		brand = ' ',
		model = 'seasparrow',
		price = 500000,
		category = 'helicopters',
		hash = `seasparrow`,
	},
	supervolito = {
		name = 'SuperVolito',
		brand = ' ',
		model = 'supervolito',
		price = 750000,
		category = 'helicopters',
		hash = `supervolito`,
	},
	supervolito2 = {
		name = 'SuperVolito Carbon',
		brand = ' ',
		model = 'supervolito2',
		price = 1000000,
		category = 'helicopters',
		hash = `supervolito2`,
	},
	swift = {
		name = 'Swift',
		brand = ' ',
		model = 'swift',
		price = 750000,
		category = 'helicopters',
		hash = `swift`,
	},
	swift2 = {
		name = 'Swift Deluxe',
		brand = ' ',
		model = 'swift2',
		price = 1000000,
		category = 'helicopters',
		hash = `swift2`,
	},
	volatus = {
		name = 'Volatus',
		brand = ' ',
		model = 'volatus',
		price = 1250000,
		category = 'helicopters',
		hash = `volatus`,
	},
	annihilator = {
		name = 'Annihilator',
		brand = ' ',
		model = 'annihilator',
		price = 900000,
		category = 'helicopters',
		hash = `annihilator`,
	},
	clique2 = {
		name = 'Clique Wagon',
		brand = 'Vapid',
		model = 'clique2',
		price = 15000,
		category = 'muscle',
		hash = `clique2`,
	},
	monstrociti = {
		name = 'MonstroCiti',
		brand = 'Maibatsu',
		model = 'monstrociti',
		price = 90000,
		category = 'suvs',
		hash = `monstrociti`,
	},
	ratel = {
		name = 'Ratel',
		brand = 'Vapid',
		model = 'ratel',
		price = 115000,
		category = 'offroad',
		hash = `ratel`,
	},
	stingertt = {
		name = 'Itali GTO Stinger TT',
		brand = 'Grotti',
		model = 'stingertt',
		price = 500000,
		category = 'super',
		hash = `stingertt`,
	},
	speedo4 = {
		name = 'Speedo Custom',
		brand = 'Vapid',
		model = 'speedo4',
		price = 30000,
		category = 'vans',
		hash = `speedo4`,
	},
	l35 = {
		name = 'Walton L35',
		brand = 'Declasse',
		model = 'l35',
		price = 40000,
		category = 'offroad',
		hash = `l35`,
	},
	buffalo5 = {
		name = 'Buffalo EVX',
		brand = 'Bravado',
		model = 'buffalo5',
		price = 260000,
		category = 'sports',
		hash = `buffalo5`,
	},
	coureur = {
		name = 'La Coureuse',
		brand = 'Penaud',
		model = 'coureur',
		price = 310000,
		category = 'tuner',
		hash = `coureur`,
	},
	inductor = {
		name = 'Inductor',
		brand = 'Coil',
		model = 'inductor',
		price = 3000,
		category = 'cycles',
		hash = `inductor`,
	},
	inductor2 = {
		name = 'Junk Energy Inductor',
		brand = 'Coil',
		model = 'inductor2',
		price = 3000,
		category = 'cycles',
		hash = `inductor2`,
	},
	brigham = {
		name = 'Brigham',
		brand = 'Albany',
		model = 'brigham',
		price = 12000,
		category = 'muscle',
		hash = `brigham`,
	},
	streamer216 = {
		name = 'Mammoth Streamer 216',
		brand = ' ',
		model = 'streamer216',
		price = 190000,
		category = 'planes',
		hash = `streamer216`,
	},
	tezeract = {
		name = 'Tezeract',
		brand = 'Pegassi',
		model = 'tezeract',
		price = 1100000,
		category = 'super',
		hash = `tezeract`,
	},
	cyclone = {
		name = 'Cyclone',
		brand = 'Coil',
		model = 'cyclone',
		price = 620000,
		category = 'super',
		hash = `cyclone`,
	},
	omnisegt = {
		name = 'Omnis e-GT',
		brand = 'Obey',
		model = 'omnisegt',
		price = 390000,
		category = 'sports',
		hash = `omnisegt`,
	},
	khamelion = {
		name = 'Khamelion',
		brand = 'Hijak',
		model = 'khamelion',
		price = 385000,
		category = 'sports',
		hash = `khamelion`,
	},
	neon = {
		name = 'Neon',
		brand = 'Pfister',
		model = 'neon',
		price = 145000,
		category = 'sports',
		hash = `neon`,
	},
	raiden = {
		name = 'Raiden',
		brand = 'Coil',
		model = 'raiden',
		price = 130000,
		category = 'sports',
		hash = `raiden`,
	},
	voltic = {
		name = 'Voltic',
		brand = 'Coil',
		model = 'voltic',
		price = 135000,
		category = 'sports',
		hash = `voltic`,
	},
	iwagen = {
		name = 'I-Wagen',
		brand = 'Obey',
		model = 'iwagen',
		price = 130000,
		category = 'suvs',
		hash = `iwagen`,
	},
	surge = {
		name = 'Surge',
		brand = 'Cheval',
		model = 'surge',
		price = 33000,
		category = 'compacts',
		hash = `surge`,
	},
	dilettante = {
		name = 'Dilettante',
		brand = 'Karin',
		model = 'dilettante',
		price = 15000,
		category = 'compacts',
		hash = `dilettante`,
	},
	------------

	nkvigero2 = {
		name = 'PD Vigero ZX (I)',
		brand = 'Declasse',
		model = 'nkvigero2',
		price = 100000,
		category = 'emergency',
		hash = `nkvigero2`,
	},
	nkgauntlet4 = {
		name = 'PD Gauntlet Hellfire (I)',
		brand = 'Bravado',
		model = 'nkgauntlet4',
		price = 95000,
		category = 'emergency',
		hash = `nkgauntlet4`,
	},
	nkdominator3 = {
		name = 'PD Dominator GTX (I)',
		brand = 'Vapid',
		model = 'nkdominator3',
		price = 80000,
		category = 'emergency',
		hash = `nkdominator3`,
	},
	nkcoquette = {
		name = 'PD Coquette (I)',
		brand = 'Invetero',
		model = 'nkcoquette',
		price = 90000,
		category = 'emergency',
		hash = `nkcoquette`,
	},

	nkbison = {
		name = 'PD Bison (T)',
		brand = 'Bravado',
		model = 'nkbison',
		price = 40000,
		category = 'emergency',
		hash = `nkbison`,
	},
	nkcaracara2 = {
		name = 'PD Caracara 4x4 (T)',
		brand = 'Vapid',
		model = 'nkcaracara2',
		price = 50000,
		category = 'emergency',
		hash = `nkcaracara2`,
	},
	nkstx = {
		name = 'PD Buffalo STX',
		brand = 'Bravado',
		model = 'nkstx',
		price = 40000,
		category = 'emergency',
		hash = `nkstx`,
	},
	nkballer7 = {
		name = 'PD Baller ST',
		brand = 'Gallivanter',
		model = 'nkballer7',
		price = 35000,
		category = 'emergency',
		hash = `nkballer7`,
	},
	nkfugitive = {
		name = 'PD Fugitive',
		brand = 'Cheval',
		model = 'nkfugitive',
		price = 35000,
		category = 'emergency',
		hash = `nkfugitive`,
	},
	nklandstalker2 = {
		name = 'PD Landstalker XL',
		brand = 'Dundreary',
		model = 'nklandstalker2',
		price = 35000,
		category = 'emergency',
		hash = `nklandstalker2`,
	},
	nktailgaters = {
		name = 'PD Tailgater S',
		brand = 'Obey',
		model = 'nktailgaters',
		price = 30000,
		category = 'emergency',
		hash = `nktailgaters`,
	},
	nktorrence = {
		name = 'PD Emergency Interceptor',
		brand = 'Vapid',
		model = 'nktorrence',
		price = 25000,
		category = 'emergency',
		hash = `nktorrence`,
	},
	nkcruiser = {
		name = 'PD emergency Cruiser',
		brand = 'Vapid',
		model = 'nkcruiser',
		price = 25000,
		category = 'emergency',
		hash = `nkcruiser`,
	},
	nkshinobi = {
		name = 'PD Shinobi (M) (LSPD Only)',
		brand = 'Nagasaki',
		model = 'nkshinobi',
		price = 40000,
		category = 'emergency',
		hash = `nkshinobi`,
	},
	nkmanchez3 = {
		name = 'PD Manchez (M)',
		brand = 'Maibatsu',
		model = 'nkmanchez3',
		price = 30000,
		category = 'emergency',
		hash = `nkmanchez3`,
	},
	nkbf400 = {
		name = 'PD BF400 (M)',
		brand = ' ',
		model = 'nkbf400',
		price = 30000,
		category = 'emergency',
		hash = `nkbf400`,
	},
	nksvolito = {
		name = 'PD Super Volito',
		brand = ' ',
		model = 'nksvolito',
		price = 250000,
		category = 'emergency',
		hash = `nksvolito`,
	},
	nkbuzzard = {
		name = 'PD Buzzard',
		brand = ' ',
		model = 'nkbuzzard',
		price = 250000,
		category = 'emergency',
		hash = `nkbuzzard`,
	},
	nksvolitoems = {
		name = 'EMS Super Volito',
		brand = ' ',
		model = 'nksvolitoems',
		price = 250000,
		category = 'emergency',
		hash = `nksvolitoems`,
	},
	nkambulance = {
		name = 'EMS Ambulance',
		brand = ' ',
		model = 'nkambulance',
		price = 25000,
		category = 'emergency',
		hash = `nkambulance`,
	},
	nkballer7ems = {
		name = 'EMS Baller ST',
		brand = 'Gallavanter',
		model = 'nkballer7ems',
		price = 35000,
		category = 'emergency',
		hash = `nkballer7ems`,
	},
	nkcaracara2ems = {
		name = 'EMS Caracara 4x4 (T)',
		brand = 'Vapid',
		model = 'nkcaracara2ems',
		price = 50000,
		category = 'emergency',
		hash = `nkcaracara2ems`,
	},
	nkgranger2ems = {
		name = 'EMS Granger 3600LX',
		brand = 'Declasse',
		model = 'nkgranger2ems',
		price = 35000,
		category = 'emergency',
		hash = `nkgranger2ems`,
	},
	nklandstalker2ems = {
		name = 'EMS Landstalker XL',
		brand = 'Declasse',
		model = 'nklandstalker2ems',
		price = 35000,
		category = 'emergency',
		hash = `nklandstalker2ems`,
	},
	nkstxems = {
		name = 'EMS Buffalo STX',
		brand = 'Bravado',
		model = 'nkstxems',
		price = 40000,
		category = 'emergency',
		hash = `nkstxems`,
	},
	enladder = {
		name = 'FD Ladder',
		brand = 'Pierce',
		model = 'enladder',
		price = 25000,
		category = 'emergency',
		hash = `enladder`,
	},
	sheavas = {
		name = 'Sheava',
		brand = 'Emperor',
		model = 'sheavas',
		price = 525000,
		category = 'super',
		hash = `sheavas`,
	},
	caracaran = {
		name = 'Caracara',
		brand = 'Vapid',
		model = 'caracaran',
		price = 125000,
		category = 'offroad',
		hash = `caracaran`,
	},
	sandstorm = {
		name = 'Sandstorm',
		brand = 'Vapid',
		model = 'sandstorm',
		price = 140000,
		category = 'offroad',
		hash = `sandstorm`,
	},
	vulture = {
		name = 'Vulture',
		brand = 'Bravado',
		model = 'vulture',
		price = 130000,
		category = 'muscle',
		hash = `vulture`,
	},
	atlas = {
		name = 'Atlas',
		brand = 'Karin',
		model = 'atlas',
		price = 30000,
		category = 'vans',
		hash = `atlas`,
	},
	bansheepo = {
		name = 'Banshee',
		brand = 'Bravado',
		model = 'bansheepo',
		price = 430000,
		category = 'super',
		hash = `bansheepo`,
	},
	clubgtr = {
		name = 'Club GTR',
		brand = 'BF',
		model = 'clubgtr',
		price = 110000,
		category = 'sportsclassics',
		hash = `clubgtr`,
	},
	cometold = {
		name = 'Comet Classic',
		brand = 'Pfister',
		model = 'cometold',
		price = 190000,
		category = 'sportsclassics',
		hash = `cometold`,
	},
	cwagon = {
		name = 'Compact Wagon',
		brand = 'Schyster',
		model = 'cwagon',
		price = 40000,
		category = 'compacts',
		hash = `cwagon`,
	},
	cycloneex0 = {
		name = 'EX-0',
		brand = 'Cyclone',
		model = 'cycloneex0',
		price = 470000,
		category = 'electric',
		hash = `cycloneex0`,
	},
	dubsta22 = {
		name = 'Dubsta',
		brand = 'Benefactor',
		model = 'dubsta22',
		price = 270000,
		category = 'suvs',
		hash = `dubsta22`,
	},
	eva = {
		name = 'EVA',
		brand = 'Hijak',
		model = 'eva',
		price = 30000,
		category = 'compacts',
		hash = `eva`,
	},
	gauntletc = {
		name = 'Gauntlet Classic',
		brand = 'Bravado',
		model = 'gauntletc',
		price = 160000,
		category = 'muscle',
		hash = `gauntletc`,
	},
	italigtr = {
		name = 'Itali GTR',
		brand = 'Grotti',
		model = 'italigtr',
		price = 560000,
		category = 'super',
		hash = `italigtr`,
	},
	trailw = {
		name = 'Trailwilder',
		brand = 'Annis',
		model = 'trailw',
		price = 60000,
		category = 'offroad',
		hash = `trailw`,
	},
	turtle = {
		name = 'Turtle',
		brand = 'Karin',
		model = 'turtle',
		price = 40000,
		category = 'compacts',
		hash = `turtle`,
	},
	paradox = {
		name = 'Paradox',
		brand = 'Willard',
		model = 'paradox',
		price = 40000,
		category = 'muscle',
		hash = `paradox`,
	},
	picadorexr = {
		name = 'Picador EXR',
		brand = 'Cheval',
		model = 'picadorexr',
		price = 240000,
		category = 'muscle',
		hash = `picadorexr`,
	},
	uranus = {
		name = 'Uranus',
		brand = 'Vapid',
		model = 'uranus',
		price = 140000,
		category = 'muscle',
		hash = `uranus`,
	},
	coquette5 = {
		name = 'Coquette D5',
		brand = 'Inverto',
		model = 'coquette5',
		price = 140000,
		category = 'muscle',
		hash = `coquette5`,
	},

	---- NEW 15/12/2023
	aleutian = {
		name = 'Aleutian',
		brand = 'Vapid',
		model = 'aleutian',
		price = 34000,
		category = 'suvs',
		hash = `aleutian`,
	},
	asterope2 = {
		name = 'Asterope GZ',
		brand = 'Karin',
		model = 'asterope2',
		price = 30000,
		category = 'sedans',
		hash = `asterope2`,
	},
	baller8 = {
		name = 'Baller ST-D',
		brand = 'Gallivanter',
		model = 'baller8',
		price = 45000,
		category = 'suvs',
		hash = `baller8`,
	},
	cavalcade3 = {
		name = 'Cavalcade XL',
		brand = 'Albany',
		model = 'cavalcade3',
		price = 45000,
		category = 'suvs',
		hash = `cavalcade3`,
	},
	dominator9 = {
		name = 'Dominator GT',
		brand = 'Vapid',
		model = 'dominator9',
		price = 320000,
		category = 'muscle',
		hash = `dominator9`,
	},
	dorado = {
		name = 'Dorado',
		brand = 'Bravado',
		model = 'dorado',
		price = 32500,
		category = 'muscle',
		hash = `dorado`,
	},
	fr36 = {
		name = 'FR-36',
		brand = 'Fathom',
		model = 'fr36',
		price = 140000,
		category = 'sports',
		hash = `fr36`,
	},
	impaler5 = {
		name = 'Impaler SZ',
		brand = 'Declasse',
		model = 'impaler5',
		price = 30000,
		category = 'muscle',
		hash = `impaler5`,
	},
	impaler6 = {
		name = 'Impaler LX',
		brand = 'Declasse',
		model = 'impaler6',
		price = 30000,
		category = 'muscle',
		hash = `impaler6`,
	},
	terminus = {
		name = 'Mesa S',
		brand = 'Canis',
		model = 'terminus',
		price = 145000,
		category = 'sedans',
		hash = `terminus`,
	},
	turismo3 = {
		name = 'Turismo Omaggio',
		brand = 'Grotti',
		model = 'turismo3',
		price = 565000,
		category = 'super',
		hash = `turismo3`,
	},
	vigero3 = {
		name = 'Vigero ZX Convertible',
		brand = 'Declasse',
		model = 'vigero3',
		price = 320000,
		category = 'muscle',
		hash = `vigero3`,
	},
	vivanite = {
		name = 'Vivernite',
		brand = 'Karin',
		model = 'vivanite',
		price = 45000,
		category = 'sports',
		hash = `vivanite`,
	},
}